### ISSUE TITLE
PHP Fatal Error on listing packages

### ISSUE THREAD

**Issue by playmono** [wp-cli/package-command#59] opened 2017-12-19 09:44 UTC
Hi,

Running this command:
`./wp-cli.phar package list`

Im having this PHP Fatal Error:
```
PHP Fatal error:  Uncaught RuntimeException: Failed to execute git clone --mirror 'git@github.com:wp-cli/admin-command.git' '/home/user/.cache/composer/vcs/git-github.com-wp-cli-admin-command.git/'

 in phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Util/Git.php:310
Stack trace:
#0 phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Util/Git.php(199): Composer\Util\Git->throwException('Failed to execu...', 'git@github.com:...')
#1 phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Util/Git.php(226): Composer\Util\Git->runCommand(Object(Closure), 'git@github.com:...', NULL, true)
#2 phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Repository/Vcs/GitDriver.php(60): Composer\Util\Git->syncMirror('git@github.com:...', '/home/user...')
#3 phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(508): Composer\Repository\Vcs\GitDri in phar:///var/www/bin/wp-cli.phar/vendor/composer/composer/src/Composer/Util/Git.php on line 310
```

The thing is I dont have permission to execute this line `git clone --mirror 'git@github.com:wp-cli/admin-command.git' '/home/user/.cache/composer/vcs/git-github.com-wp-cli-admin-command.git/'`, so despite my error I think wp-cli should control the RuntimeException to not give a PHP Fatal Error.

**Comment by playmono** [comment] 2017-12-19 10:45
If I use for example:
`./bin/wp-cli.phar package install git@github.com:wp-cli/admin-command.git`

things works as expected, result is:
```
Installing package wp-cli/admin-command (dev-master)
Updating /home/user/.wp-cli/packages/composer.json to require the package...
Registering git@github.com:wp-cli/admin-command.git as a VCS repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Warning: Failed to execute git clone --mirror 'git@github.com:wp-cli/admin-command.git' '/home/user/.cache/composer/vcs/git-github.com-wp-cli-admin-command.git/'


---
Error: Package installation failed. Reverted composer.json
```

**Comment by gitlost** [comment] 2017-12-19 11:30
Could you try adding a personal access token https://github.com/settings/tokens (scope: repo: public_repo  Access public repositories) and then `export GITHUB_TOKEN=<token>` and see if that fixes it for you? (See also https://github.com/wp-cli/package-command/issues/44#issuecomment-340582417).

**Comment by playmono** [comment] 2017-12-19 11:40
Thank you, I was trying to fix the error, I didn't know how to solve it and your solution worked for me.

Anyway, I was saying despite my error, I think wp-cli should contemplate this case for not giving PHP Fatal Error, instead a catched Warning.

My last question is: Is necessary then, have a github account + token in order to make this library work?

Thank you.

**Comment by gitlost** [comment] 2017-12-19 11:52
>  I think wp-cli should contemplate this case for not giving PHP Fatal Error, instead a catched Warning.

Agreed!

> Is necessary then, have a github account + token in order to make this library work?

I think if you use the ssh `git@github.com:` url then yes. If you use the [recommended](https://help.github.com/articles/which-remote-url-should-i-use/) https url `https://github.com/` then no I don't think so. Could you try
```
unset GITHUB_TOKEN
./bin/wp-cli.phar package install https://github.com/wp-cli/admin-command.git
```
instead and see if that works for you?

**Comment by playmono** [comment] 2017-12-19 13:34
Library is giving me errors constantly about ssh git@github.com. But it's ok, I will try to make it work.

**Comment by gitlost** [comment] 2017-12-19 20:39
Okay ta, I did notice last time I looked that Composer uses `git@github.com:` internally anyway in some situations for some reason even if you give a https url, but the issue is complicated by what's already in your `~/.wp-cli/packages/composer.json` and whether you have a `~/.composer/auth.json` or not.

It would be good to come up with a definitive answer that can be used in error messages and in doc...

**Comment by playmono** [comment] 2017-12-20 08:55
Thank you for your answer, thats **exactly** what is happening. Even if I  delete `~/.wp-cli/`, `~/.composer `and `~/.cache` the thing dont works. I thought maybe that folders contained some cache repo related to git@github.com but didnt works.

I'm annoyed because when I started with wp-cli, everything worked perfect, and now I don't know what changed (Tried to "restore to initial mode" deleting all that folders etc but didnt works).

I will looking into this problem this days and hopefully will bring a solution.

Thanks.

**Comment by playmono** [comment] 2017-12-21 10:43
In my research I discovered that command: `wp package list` connects with `https://api.github.com/repos/wp-cli/admin-command` and this URL is giving me:
```
{
  "message": "API rate limit exceeded for xx.xxx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
Then sometimes I can list my packages and sometimes not.

Is this the correct behaviour of the wp-cli?

Thank you.

**Comment by gitlost** [comment] 2017-12-21 11:14
Ah you're getting rate limiting, then this does require the `GITHUB_TOKEN` to be set to up your [quota](https://developer.github.com/v3/#rate-limiting). If you're testing stuff then you can run into this especially.

> Is this the correct behaviour of the wp-cli?

Well that particular issue is out of wp-cli's hands, and should be workaroundable using `GITHUB_TOKEN`, so "yes"!

It does make it awkward to test whether using the https url rather than the ssh url would allow one to not have to have a token.

Do you have particular circumstances where needing to set up a token is not practical or convenient?

**Comment by playmono** [comment] 2017-12-21 11:57
Setting a token is very unpractical and inconvenient if I want to make an application using wp-cli that is replicated in a lot of servers analyzing wordpress installations. I mean, dont want create a github account just for this, and of course I dont want to use my personal github account for this.

In adittion, what's the point in connecting to github API when I just want to list my packages that I installed **locally**? I don't get it.

I think this approach is more interesting.
 #60 

Result is:

> +---------------------------+-------------+------------+---------------------------+---------------------------+
| name                      | authors     | version    | update                    | update_version            |
+---------------------------+-------------+------------+---------------------------+---------------------------+
| wp-cli/admin-command      |             | dev-master | Error whith Github Driver | Error whith Github Driver |
| wp-cli/wp-super-cache-cli | WP-CLI Team | dev-master | none                      |                           |
+---------------------------+-------------+------------+---------------------------+---------------------------+

**Comment by gitlost** [comment] 2017-12-21 12:15
> what's the point in connecting to github API when I just want to list my packages that I installed locally?

The reason it's doing it is to check for updates. It's also why it's so slow. Maybe a package list option to suppress this would be worth having?

**Comment by playmono** [comment] 2017-12-21 13:05
Well, that will be the perfect solution I think. Anyway I see that more as a feature than a bug fixed.

**Comment by gitlost** [comment] 2017-12-21 13:16
Yes, it would be a new feature, with a separate new issue.

**Comment by gitlost** [comment] 2018-01-03 13:14
Going to close this via PR https://github.com/wp-cli/package-command/pull/60 and the new issues https://github.com/wp-cli/package-command/issues/61 and https://github.com/wp-cli/package-command/issues/62. Thanks for all your help @playmono !

**Closed by gitlost** 2018-01-03 13:14 UTC
Labels: bug, command:package, command:package-list
