### ISSUE TITLE
Phar v1.4.0 produces errors in Composer autoloader

### ISSUE THREAD

**Issue by schlessera** [wp-cli/package-command#44] opened 2017-10-27 15:59 UTC
The Phar download of version 1.4.0 produces errors in the Composer autoloader. It tries to include the PHPCS Standards Installer package, which is not part of the Phar however (as it is a dev-dependency).

![image 2017-10-27 at 5 45 16 pm](https://user-images.githubusercontent.com/83631/32112881-d3a86068-bb3e-11e7-99c1-06969175bd86.png)

As that installer is a Composer plugin, it becomes active as soon as Composer becomes active, so just stripping it from the Phar as a dev-dependency would mean we'll have to rebuild the Composer autoloader for the Phar with `--no-dev` first.

**Comment by danielbachhuber** [comment] 2017-10-27 16:44
Ugh, annoying. I don't consider it severe, but it'd be nice to have fixed in the stable build sooner rather than later.

We should likely release a v1.4.1 in the next few weeks.

**Comment by schlessera** [comment] 2017-10-27 16:54
@danielbachhuber Can you reproduce this?  I wasn't sure whether it might not be an issue with my local setup...

**Comment by danielbachhuber** [comment] 2017-10-27 16:56
Yes, I've reproduced with the steps indicated in your screenshot.

**Comment by gitlost** [comment] 2017-10-30 17:37
I can't reproduce this locally. What's triggering the lookup of `Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin`? (Maybe a global require in `~/.composer/composer.json`??)

Anyway I presume the autoload stripping https://github.com/wp-cli/wp-cli/blob/v1.4.0/utils/make-phar.php#L58 should be updated for the extra entries "dealerdirect/phpcodesniffer-composer-installer", "wimg/php-compatibility", and "wp-coding-standards/wpcs", as opposed to adding them to the phar?

**Comment by gitlost** [comment] 2017-10-30 18:03
I should add though that the tests tagged `@github-api` in`features/package-install.feature`, which aren't executed by Travis, don't work for me locally either, even after fixing https://github.com/wp-cli/package-command/blob/v1.0.7/features/package-install.feature#L126 to be `STDERR` instead of `STDOUT` (as it's a WP_CLI warning, not a Composer warning).

The errors I get aren't always the same, so it's probably something to do with authorisation or rate-limiting when Composer accesses github.com, but nearly always include variations of
```
Warning: Failed to execute git clone --mirror 'git@github.com:wp-cli-test/repository-name.git' '/tmp/wp-cli-home/.composer/cache/vcs/git-github.com-wp-cli-test-repository-name.git/'
```
Is there some environment var or Composer config I should be setting? I'll continue trying to debug it locally anyway (it was problems like this that made me give up on https://github.com/wp-cli/package-command/issues/43 btw).

**Comment by gitlost** [comment] 2017-10-30 20:58
Re `@github-api` tests not working, I managed to get around it by adding my `GITHUB_TOKEN` (set via https://github.com/settings/tokens) to Composer's global config:
```bash
composer config -g github-oauth.github.com <GITHUB_TOKEN>
```
(which I don't think I should have to do but that's another story), which creates a file `~/.composer/auth.json` like this:
```json
{
    "bitbucket-oauth": {},
    "github-oauth": {
        "github.com": "<GITHUB_TOKEN>"},
    "gitlab-oauth": {},
    "gitlab-token": {},
    "http-basic": {}
}
```
and then copying this into `/tmp/wp-cli-home/.composer`. So need some `GITHUB_TOKEN` handling in `Package_Command` I think.

**Comment by gitlost** [comment] 2017-11-08 17:25
Re the stack discussion https://wordpress.slack.com/archives/C02RP4T41/p1510071316000491 I think a key point is that the `given a new Phar` step was only added to test `wp cli update` (https://github.com/wp-cli/wp-cli/pull/1535) and was never meant to be a "real" phar test. Which I think makes sense as the tests themselves shouldn't try to individually test (or construct) the real phar, but leave it to the global build context to run the real phar on them.

In the case of the `given a new Phar` tests in `package-install.feature` (added https://github.com/wp-cli/wp-cli/pull/3603), the story is the same, in that it's only using the fake phar to test package version handling against different `wp-cli` version dependencies and is not interested as such in the phar or attempting to test it.

**Comment by danielbachhuber** [comment] 2017-11-13 14:39
This was fixed by https://github.com/wp-cli/wp-cli/pull/4477

**Closed by danielbachhuber** 2017-11-13 14:39 UTC
Labels: bug, command:package
